pr_review:
  # Default: true
  auto_run: true
  modules:
    # Automatically create a description summarizing the changes in pull request. 
    description:
      enabled: true
      diagram: false

    # Find potential bugs in pull request changes or related files.
    bug_hunter:
      enabled: true
      # Include fixes to possible bugs.
      suggestions: true

    # Suggest improvements to added code.
    code_suggestions:
      enabled: true

    # Suggest changes to follow defined code conventions.
    code_conventions:
      enabled: false
      # Describe your code conventions in plain text.
      conventions: |
        E.g. Exported variables, functions, classes and methods should be defined before private.
    

    # Point out any typos or grammatical errors in variable names, texts, comments.
    grammar:
      enabled: false

    # Suggest performance improvements to added code.
    performance:
      enabled: true

    # Find potential security issues in added code.
    security:
      enabled: true
