export const earlyStageInvestors = [
  "Sequoia Capital",
  "Andreessen Horowitz",
  "Accel",
  "Benchmark",
  "Founders Fund",
  "Greylock Partners",
  "Kleiner Perkins",
  "Lightspeed Venture Partners",
  "GV (formerly Google Ventures)",
  "Bessemer Venture Partners",
  "First Round Capital",
  "Union Square Ventures",
  "Index Ventures",
  "General Catalyst",
  "1984",
  "500 Startups",
  "Battery Ventures",
  "Redpoint Ventures",
  "Balderton Capital",
  "Insight Partners",
  "Floodgate Fund",
  "CRV (Charles River Ventures)",
  "Spark Capital",
  "Social Capital",
  "Ribbit Capital",
];

export const seriesAInvestors = [
  "Insight Partners",
  "IVP (Institutional Venture Partners)",
  "Menlo Ventures",
  "Canaan Partners",
  "NEA (New Enterprise Associates)",
  "Battery Ventures",
  "Bessemer Venture Partners",
  "Sapphire Ventures",
  "Sequoia Capital",
  "Matrix Partners",
  "GGV Capital",
  "Khosla Ventures",
  "Venrock",
  "True Ventures",
  "Scale Venture Partners",
  "Craft Ventures",
  "Northzone",
  "Oak HC/FT",
  "Balderton Capital",
  "Accel",
  "Index Ventures",
  "Union Square Ventures",
  "Greycroft",
  "Redpoint Ventures",
  "DFJ Growth",
];

export const founders = [
  "Brian Chesky",
  "Ben Silbermann",
  "Drew Houston",
  "Daniel Ek",
  "Arash Ferdowsi",
  "Michael Seibel",
  "Kevin Systrom",
  "Mike Krieger",
  "Melanie Perkins",
  "Evan Spiegel",
  "Bobby Murphy",
  "Travis Kalanick",
  "Garrett Camp",
  "Sean Rad",
  "Nathan Blecharczyk",
  "Joe Gebbia",
  "Ruslan Fazlyev",
  "Patrick Collison",
  "John Collison",
];
