export const top100: string[] = [
  'Softbank Investment Advisers',
  'Insight Partners',
  'Tiger Global Management',
  'Andreessen Horowitz',
  'Sequoia Capital',
  'New Enterprise Associates',
  'Tcv',
  'Lightspeed Venture Partners',
  'Accel',
  'Bessemer Venture Partners',
  'Battery Ventures',
  'Founders Fund',
  'Norwest Venture Partners',
  'Index Ventures',
  'Kleiner Perkins',
  'Ggv Capital',
  'Arch Venture Partners',
  'Bain Capital Ventures',
  'Institutional Venture Partners',
  'Khosla Ventures',
  'Canaan Partners',
  'Vivo Capital',
  'Lux Capital',
  'Redpoint Ventures',
  'Polaris Partners',
  'Greylock Partners',
  'Austin Ventures',
  'Charles River Ventures',
  'Dcm Ventures',
  'Foundation Capital',
  'Spark Capital',
  'Venrock',
  'Menlo Ventures',
  'Scale Venture Partners',
  'Atlas Venture',
  'Mayfield Fund',
  'Matrix Partners',
  'Third Rock Ventures',
  'Versant Ventures',
  'Firstmark Capital',
  'Capitalg',
  'Legend Capital',
  'Greycroft',
  'Union Square Ventures',
  'Highland Capital Partners',
  'Meritech Capital Partners',
  'Oak Investment Partners',
  'Addition',
  'Atomico Ventures',
  'Rre Ventures',
  'U.S. Venture Partners',
  'Benchmark Capital',
  'Social Capital',
  'Sevin Rosen Funds',
  'August Capital',
  'Initialized Capital',
  'Maveron',
  'Crosslink Capital',
  'Dag Ventures',
  'Morgenthaler Ventures',
  'Sofinnova Ventures',
  'Wellington Partners Venture Capital',
  'Softtech Vc',
  'Tenaya Capital',
  'Founders Circle Capital',
  'First Round Capital',
  'Advanced Technology Ventures',
  'Blumberg Capital',
  'Y Combinator',
  'Draper Fisher Jurvetson',
  'Genesis Partners',
  'Qualcomm Ventures',
  'Almaz Capital',
  'Sosv',
  'Granite Ventures',
  'Rho Ventures',
  'Lightbank',
  'Ff Venture Capital',
  'Oxford Sciences Innovation',
  'Binary Capital',
  'Columbus Nova',
  'Radius Ventures',
  'Clearstone Venture Partners',
  'Cottonwood Technology Fund',
  'Thrive Capital',
  'Lighter Capital',
  'Gv',
  'Contrary',
  'Antler',
  'Chimera Capital',
  'Galen Partners',
  'Rothenberg Ventures',
  'Nova Founders Capital',
  'Syndicateroom',
  'Mercia Fund Management',
  'Azure Capital Partners',
  'Gaingels',
  '500 Global',
  'Keiretsu Forum',
  'Fj Labs',
];