name: Run Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build, Lint, Test and Deploy
    environment: production
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn run build
      - name: Deploy Apps Script
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ vars.SCRIPT_ID }}
          command: "push"
      - name: Link to deployment
        run:
          echo "Deployed to
          https://docs.google.com/spreadsheets/d/1eunUazlR9qeNVkH29ihF9MCrLtmBNAANByzck2HceX4"
